name: Generate VRBO .ics

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - run: pip install icalendar pytz
      - run: python generate_calendar.py
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/vrbo_blocker.ics
          git commit -m "Update .ics"
          git push
